In [45]:
import pandas as pd
from plotting import CandlePlot
pd.set_option("display.max_columns", None)

In [46]:
df_ma_res = pd.read_pickle("../data/ma_res.pkl")
df_ma_trades = pd.read_pickle("../data/ma_trades.pkl")

In [47]:
df_ma_res.granularity.unique()

array(['H1', 'H4', 'H2'], dtype=object)

In [48]:
df_ma_res_h1 = df_ma_res[df_ma_res.granularity == "H1"].copy()
df_ma_trades_h1 = df_ma_trades[df_ma_trades.granularity == "H1"].copy()

In [49]:
df_ma_trades.shape

(53054, 32)

In [50]:
df_ma_res_h1.columns

Index(['pair', 'num_trades', 'total_gain', 'mean_gain', 'min_gain', 'max_gain',
       'ma_l', 'ma_s', 'cross', 'granularity'],
      dtype='object')

In [51]:
df_cross_summary = df_ma_res_h1[['pair', 'num_trades', 'total_gain', 'cross']].copy()

In [52]:
df_cross_summary

        pair  num_trades  total_gain         cross
0    EUR_USD         216        -617   MA_10_MA_20
1    EUR_USD         112        -613   MA_10_MA_40
2    EUR_USD         108         -56   MA_20_MA_40
3    EUR_USD         112        -114   MA_30_MA_40
4    EUR_USD          90        -998   MA_10_MA_80
..       ...         ...         ...           ...
235  CAD_JPY          42        -863  MA_40_MA_120
236  CAD_JPY          63       -1325  MA_10_MA_150
237  CAD_JPY          42        -320  MA_20_MA_150
238  CAD_JPY          38       -1014  MA_30_MA_150
239  CAD_JPY          36       -1262  MA_40_MA_150

[240 rows x 4 columns]

In [53]:
df_cross_gr = df_cross_summary.groupby(by="cross", as_index=False).sum()
df_cross_gr.sort_values(by="total_gain", ascending=False, inplace=True)

In [54]:
df_cross_gr

,cross,pair,num_trades,total_gain
2,MA_10_MA_20,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,3106,839
11,MA_30_MA_40,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,1788,-6250
3,MA_10_MA_40,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,1780,-6767
15,MA_40_MA_80,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,827,-7788
4,MA_10_MA_80,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,1157,-8805
7,MA_20_MA_40,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,1590,-11457
12,MA_30_MA_80,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,876,-11570
8,MA_20_MA_80,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,948,-12175
13,MA_40_MA_120,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,626,-13585
10,MA_30_MA_150,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,594,-13748
0,MA_10_MA_120,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,962,-13909
9,MA_30_MA_120,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,680,-15109
14,MA_40_MA_150,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,533,-15560
5,MA_20_MA_120,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,768,-16036
6,MA_20_MA_150,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,701,-16337
1,MA_10_MA_150,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,905,-17771

In [55]:
total_pairs = len(df_ma_res_h1.pair.unique())

In [56]:
total_pairs

15

In [57]:
temp = df_ma_res_h1[df_ma_res_h1.cross == "MA_10_MA_40"]

In [58]:
temp[temp.total_gain > 0].shape[0]

4

In [60]:
for c in df_ma_res_h1.cross.unique():
    temp = df_ma_res_h1[df_ma_res_h1.cross == c]
    pg = temp[temp.total_gain > 0].shape[0]
    print(f"{c} pg:{pg} perc gain:{(pg / total_pairs) * 100:.0f}%")

MA_10_MA_20 pg:9 perc gain:60%
MA_10_MA_40 pg:4 perc gain:27%
MA_20_MA_40 pg:3 perc gain:20%
MA_30_MA_40 pg:4 perc gain:27%
MA_10_MA_80 pg:6 perc gain:40%
MA_20_MA_80 pg:3 perc gain:20%
MA_30_MA_80 pg:3 perc gain:20%
MA_40_MA_80 pg:5 perc gain:33%
MA_10_MA_120 pg:4 perc gain:27%
MA_20_MA_120 pg:2 perc gain:13%
MA_30_MA_120 pg:2 perc gain:13%
MA_40_MA_120 pg:1 perc gain:7%
MA_10_MA_150 pg:1 perc gain:7%
MA_20_MA_150 pg:1 perc gain:7%
MA_30_MA_150 pg:2 perc gain:13%
MA_40_MA_150 pg:0 perc gain:0%

In [67]:
cross = "MA_10_MA_20"
df_MA_10_MA_20 = df_ma_res_h1[df_ma_res_h1.cross == cross].copy()
df_MA_10_MA_20.sort_values(by="total_gain", ascending=False, inplace=True)

In [68]:
df_MA_10_MA_20

,pair,num_trades,total_gain,mean_gain,min_gain,max_gain,ma_l,ma_s,cross,granularity
160,GBP_CAD,203,2404,11,-194,543,MA_20,MA_10,MA_10_MA_20,H1
128,GBP_JPY,187,1409,7,-425,480,MA_20,MA_10,MA_10_MA_20,H1
144,GBP_AUD,205,979,4,-244,727,MA_20,MA_10,MA_10_MA_20,H1
32,EUR_JPY,191,313,1,-352,521,MA_20,MA_10,MA_10_MA_20,H1
112,GBP_USD,213,308,1,-249,388,MA_20,MA_10,MA_10_MA_20,H1
80,USD_JPY,198,258,1,-355,662,MA_20,MA_10,MA_10_MA_20,H1
192,AUD_JPY,195,175,0,-241,281,MA_20,MA_10,MA_10_MA_20,H1
64,EUR_CAD,199,163,0,-160,281,MA_20,MA_10,MA_10_MA_20,H1
208,AUD_CAD,204,128,0,-129,200,MA_20,MA_10,MA_10_MA_20,H1
224,CAD_JPY,207,-48,0,-259,306,MA_20,MA_10,MA_10_MA_20,H1
0,EUR_USD,216,-617,-2,-219,216,MA_20,MA_10,MA_10_MA_20,H1
48,EUR_AUD,221,-693,-3,-196,396,MA_20,MA_10,MA_10_MA_20,H1
16,EUR_GBP,221,-881,-3,-96,163,MA_20,MA_10,MA_10_MA_20,H1
176,AUD_USD,215,-1012,-4,-133,163,MA_20,MA_10,MA_10_MA_20,H1
96,USD_CAD,231,-2047,-8,-210,197,MA_20,MA_10,MA_10_MA_20,H1

In [69]:
df_gains = df_ma_trades_h1[(df_ma_trades_h1.cross==cross)&
                           (df_ma_trades_h1.pair=="CAD_JPY")].copy()